<a href="https://colab.research.google.com/github/Vignesh424/Milk_Quality_Classify/blob/main/Milk_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
#!pip install scikit-learn==1.2.0

In [41]:
#Import Packages
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

In [42]:
#Read the dataset
data_med = pd.read_csv('/content/milknew.csv')
data_med.head()

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour   Grade
0  6.6          35      1     0     1          0     254    high
1  6.6          36      0     1     0          1     253    high
2  8.5          70      1     1     1          1     246     low
3  9.5          34      1     1     0          1     255     low
4  6.6          37      0     0     0          0     255  medium

In [43]:
#Shape
data_med.shape

(1059, 8)

In [44]:
#info
data_med.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   pH          1059 non-null   float64
 1   Temprature  1059 non-null   int64  
 2   Taste       1059 non-null   int64  
 3   Odor        1059 non-null   int64  
 4   Fat         1059 non-null   int64  
 5   Turbidity   1059 non-null   int64  
 6   Colour      1059 non-null   int64  
 7   Grade       1059 non-null   object 
dtypes: float64(1), int64(6), object(1)
memory usage: 66.3+ KB


In [45]:
#Describe
data_med.describe()

pH   Temprature        Taste         Odor         Fat   \
count  1059.000000  1059.000000  1059.000000  1059.000000  1059.000000   
mean      6.630123    44.226629     0.546742     0.432483     0.671388   
std       1.399679    10.098364     0.498046     0.495655     0.469930   
min       3.000000    34.000000     0.000000     0.000000     0.000000   
25%       6.500000    38.000000     0.000000     0.000000     0.000000   
50%       6.700000    41.000000     1.000000     0.000000     1.000000   
75%       6.800000    45.000000     1.000000     1.000000     1.000000   
max       9.500000    90.000000     1.000000     1.000000     1.000000   

         Turbidity       Colour  
count  1059.000000  1059.000000  
mean      0.491029   251.840415  
std       0.500156     4.307424  
min       0.000000   240.000000  
25%       0.000000   250.000000  
50%       0.000000   255.000000  
75%       1.000000   255.000000  
max       1.000000   255.000000

In [46]:
#Features and the Target
X = data_med.drop(columns=['Grade'], axis=1)
Y = data_med['Grade']

In [47]:
#Split into train and test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=2)

In [48]:
#Algorithm
model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

DecisionTreeClassifier()

In [49]:
#Predict the Value
Y_Pred = model.predict(X_test)

In [50]:
#confusion Matrix
print(metrics.confusion_matrix(Y_test, Y_Pred))

[[ 66   1   0]
 [  0 105   0]
 [  0   0  93]]


In [51]:
#Present the findings using metrics of regression
print("Accuracy:", metrics.accuracy_score(Y_test, Y_Pred))
print("Precision:", metrics.precision_score(Y_test, Y_Pred, average="macro"))
print("Recall:", metrics.recall_score(Y_test, Y_Pred, average="macro"))
print("F1 Score:", metrics.f1_score(Y_test, Y_Pred, average="macro"))

Accuracy: 0.9962264150943396
Precision: 0.9968553459119497
Recall: 0.9950248756218905
F1 Score: 0.9959139555048759


In [52]:
#Generate a Pickle file
import pickle
check= open('milk2.pkl', 'wb')
pickle.dump(model, check)